services:
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
      volumes:
        - ./data:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres88